homepage:
    pattern:  /
    defaults: { _controller: AcmeManagerBundle:Calendar:index }
    
jsonData:
    pattern:  /jsonData.json
    defaults: { _controller: AcmeManagerBundle:Calendar:jsonData }   
    options:
        expose: true