homepage:
    pattern:  /
    defaults: { _controller: AcmeManagerBundle:Default:index }
    
calendar:
    pattern:  /calendar
    defaults: { _controller: AcmeManagerBundle:Calendar:index }
    
wallet:
    pattern:  /wallet
    defaults: { _controller: AcmeManagerBundle:Wallet:index }
    
calendar_data:
    pattern:  /calendar/data/{from}/{to}.json
    defaults: { _controller: AcmeManagerBundle:Calendar:data }
    options:
        expose: true
